# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from static.imagens import youtube
from pytube import YouTube
from mhyt import yt_download
import os


class UiMainWindow(object):
    def setupui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 373)
        self._centralwidget = QtWidgets.QWidget(MainWindow)
        self._centralwidget.setObjectName("centralwidget")
        self._bt_download = QtWidgets.QPushButton(self._centralwidget)
        self._bt_download.setGeometry(QtCore.QRect(170, 270, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._bt_download.setFont(font)
        self._bt_download.setObjectName("bt_download")
        self.l_logo = QtWidgets.QLabel(self._centralwidget)
        self.l_logo.setGeometry(QtCore.QRect(50, 30, 121, 111))
        self.l_logo.setStyleSheet("image:url(:/youtube/unnamed.png)")
        self.l_logo.setText("")
        self.l_logo.setObjectName("l_logo")
        self.l_title = QtWidgets.QLabel(self._centralwidget)
        self.l_title.setGeometry(QtCore.QRect(170, 40, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l_title.setFont(font)
        self.l_title.setObjectName("l_title")
        self.widget = QtWidgets.QWidget(self._centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 270, 48, 46))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_mp4 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_mp4.setFont(font)
        self.rb_mp4.setObjectName("rb_mp4")
        self.verticalLayout.addWidget(self.rb_mp4)
        self.rb_mp3 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_mp3.setFont(font)
        self.rb_mp3.setAutoFillBackground(False)
        self.rb_mp3.setObjectName("rb_mp3")
        self.verticalLayout.addWidget(self.rb_mp3)
        self.widget1 = QtWidgets.QWidget(self._centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 220, 191, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_titulo = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.l_titulo.setFont(font)
        self.l_titulo.setObjectName("l_titulo")
        self.horizontalLayout.addWidget(self.l_titulo)
        self.txt_titulo = QtWidgets.QLineEdit(self.widget1)
        self.txt_titulo.setObjectName("txt_titulo")
        self.horizontalLayout.addWidget(self.txt_titulo)
        self.widget2 = QtWidgets.QWidget(self._centralwidget)
        self.widget2.setGeometry(QtCore.QRect(20, 170, 301, 31))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_link = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.l_link.setFont(font)
        self.l_link.setObjectName("l_link")
        self.horizontalLayout_2.addWidget(self.l_link)
        self.txt_link = QtWidgets.QLineEdit(self.widget2)
        self.txt_link.setText("")
        self.txt_link.setObjectName("txt_link")
        self.horizontalLayout_2.addWidget(self.txt_link)
        MainWindow.setCentralWidget(self._centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._bt_download.setText(_translate("MainWindow", "Download"))
        self.l_logo.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/youtube/unnamed.png\"/></p></body></html>"))
        self.l_title.setText(_translate("MainWindow", "Hc Download"))
        self.rb_mp4.setText(_translate("MainWindow", "mp4"))
        self.rb_mp3.setText(_translate("MainWindow", "mp3"))
        self.l_titulo.setText(_translate("MainWindow", "Titulo:"))
        self.l_link.setText(_translate("MainWindow", "Link:"))

        self._bt_download.clicked.connect(self.download)


    def download(self):
        if self.rb_mp4.isChecked() is True:
            url = self.txt_link.text()
            titulo = self.txt_titulo.text()
            titulo_mp4 = titulo + ".mp4"
            mp4 = YouTube(url).streams.get_highest_resolution().download()
            os.rename(mp4, titulo_mp4)
        elif self.rb_mp3.isChecked() is True:
            try:
                url = self.txt_link.text()
                titulo = self.txt_titulo.text()
                titulo_mp3 = titulo + ".mp3"
                mp3 = YouTube(url).streams.get_audio_only().download()
                os.rename(mp3, titulo_mp3)
            except:
                print('não baixou ou não converteu confira ')
        else:
            print('agora foi')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
